// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: proto/littleq/v1/scheduler.proto

package lqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalingMode int32

const (
	ScalingMode_SCALING_MODE_UNSPECIFIED ScalingMode = 0
	ScalingMode_SCALING_MODE_AGGRESSIVE  ScalingMode = 1
	ScalingMode_SCALING_MODE_BALANCED    ScalingMode = 2
	ScalingMode_SCALING_MODE_ECONOMIC    ScalingMode = 3
)

// Enum value maps for ScalingMode.
var (
	ScalingMode_name = map[int32]string{
		0: "SCALING_MODE_UNSPECIFIED",
		1: "SCALING_MODE_AGGRESSIVE",
		2: "SCALING_MODE_BALANCED",
		3: "SCALING_MODE_ECONOMIC",
	}
	ScalingMode_value = map[string]int32{
		"SCALING_MODE_UNSPECIFIED": 0,
		"SCALING_MODE_AGGRESSIVE":  1,
		"SCALING_MODE_BALANCED":    2,
		"SCALING_MODE_ECONOMIC":    3,
	}
)

func (x ScalingMode) Enum() *ScalingMode {
	p := new(ScalingMode)
	*p = x
	return p
}

func (x ScalingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScalingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_littleq_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (ScalingMode) Type() protoreflect.EnumType {
	return &file_proto_littleq_v1_scheduler_proto_enumTypes[0]
}

func (x ScalingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScalingMode.Descriptor instead.
func (ScalingMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded domain payload
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Policy        *Policy                `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	DedupKey      string                 `protobuf:"bytes,7,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	SourceId      string                 `protobuf:"bytes,8,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *EnqueueRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EnqueueRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *EnqueueRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *EnqueueRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"` // true when dedup_key matched an existing task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EnqueueResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type SubscribeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	WorkerId     string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Type         string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Capabilities []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// pop_timeout controls how long Pop blocks per attempt before retrying.
	// Defaults to 5 s when zero.
	PopTimeout    *durationpb.Duration `protobuf:"bytes,4,opt,name=pop_timeout,json=popTimeout,proto3" json:"pop_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SubscribeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubscribeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SubscribeRequest) GetPopTimeout() *durationpb.Duration {
	if x != nil {
		return x.PopTimeout
	}
	return nil
}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Policy        *Policy                `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClaimedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskAssignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskAssignment) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *TaskAssignment) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskAssignment) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *TaskAssignment) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *TaskAssignment) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskAssignment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskAssignment) GetClaimedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClaimedAt
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CompleteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *FailRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FailRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FailRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

type ScalingEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// interval between successive recommendations. Defaults to 30 s when zero.
	Interval      *durationpb.Duration `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalingEventsRequest) Reset() {
	*x = ScalingEventsRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingEventsRequest) ProtoMessage() {}

func (x *ScalingEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingEventsRequest.ProtoReflect.Descriptor instead.
func (*ScalingEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ScalingEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScalingEventsRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type ScalingEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RecommendedWorkers int32                  `protobuf:"varint,2,opt,name=recommended_workers,json=recommendedWorkers,proto3" json:"recommended_workers,omitempty"`
	ArrivalRate        float64                `protobuf:"fixed64,3,opt,name=arrival_rate,json=arrivalRate,proto3" json:"arrival_rate,omitempty"` // λ — tasks/second
	ServiceRate        float64                `protobuf:"fixed64,4,opt,name=service_rate,json=serviceRate,proto3" json:"service_rate,omitempty"` // μ — tasks/second
	QueueDepth         int64                  `protobuf:"varint,5,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ScalingMode        ScalingMode            `protobuf:"varint,6,opt,name=scaling_mode,json=scalingMode,proto3,enum=littleq.v1.ScalingMode" json:"scaling_mode,omitempty"`
	Ts                 *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScalingEvent) Reset() {
	*x = ScalingEvent{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalingEvent) ProtoMessage() {}

func (x *ScalingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalingEvent.ProtoReflect.Descriptor instead.
func (*ScalingEvent) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *ScalingEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScalingEvent) GetRecommendedWorkers() int32 {
	if x != nil {
		return x.RecommendedWorkers
	}
	return 0
}

func (x *ScalingEvent) GetArrivalRate() float64 {
	if x != nil {
		return x.ArrivalRate
	}
	return 0
}

func (x *ScalingEvent) GetServiceRate() float64 {
	if x != nil {
		return x.ServiceRate
	}
	return 0
}

func (x *ScalingEvent) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *ScalingEvent) GetScalingMode() ScalingMode {
	if x != nil {
		return x.ScalingMode
	}
	return ScalingMode_SCALING_MODE_UNSPECIFIED
}

func (x *ScalingEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"` // sampling window; defaults to 60 s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricsRequest) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ArrivalRate   float64                `protobuf:"fixed64,2,opt,name=arrival_rate,json=arrivalRate,proto3" json:"arrival_rate,omitempty"`
	ServiceRate   float64                `protobuf:"fixed64,3,opt,name=service_rate,json=serviceRate,proto3" json:"service_rate,omitempty"`
	QueueDepth    int64                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	AvgWait       float64                `protobuf:"fixed64,5,opt,name=avg_wait,json=avgWait,proto3" json:"avg_wait,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricsResponse) GetArrivalRate() float64 {
	if x != nil {
		return x.ArrivalRate
	}
	return 0
}

func (x *MetricsResponse) GetServiceRate() float64 {
	if x != nil {
		return x.ServiceRate
	}
	return 0
}

func (x *MetricsResponse) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *MetricsResponse) GetAvgWait() float64 {
	if x != nil {
		return x.AvgWait
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxWait       *durationpb.Duration   `protobuf:"bytes,2,opt,name=max_wait,json=maxWait,proto3" json:"max_wait,omitempty"`
	AgingAlpha    float64                `protobuf:"fixed64,3,opt,name=aging_alpha,json=agingAlpha,proto3" json:"aging_alpha,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	ScalingMode   ScalingMode            `protobuf:"varint,5,opt,name=scaling_mode,json=scalingMode,proto3,enum=littleq.v1.ScalingMode" json:"scaling_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_littleq_v1_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_proto_littleq_v1_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetMaxWait() *durationpb.Duration {
	if x != nil {
		return x.MaxWait
	}
	return nil
}

func (x *Policy) GetAgingAlpha() float64 {
	if x != nil {
		return x.AgingAlpha
	}
	return 0
}

func (x *Policy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Policy) GetScalingMode() ScalingMode {
	if x != nil {
		return x.ScalingMode
	}
	return ScalingMode_SCALING_MODE_UNSPECIFIED
}

var File_proto_littleq_v1_scheduler_proto protoreflect.FileDescriptor

const file_proto_littleq_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	" proto/littleq/v1/scheduler.proto\x12\n" +
	"littleq.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\x0eEnqueueRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12*\n" +
	"\x06policy\x18\x05 \x01(\v2\x12.littleq.v1.PolicyR\x06policy\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\x05R\rschemaVersion\x12\x1b\n" +
	"\tdedup_key\x18\a \x01(\tR\bdedupKey\x12\x1b\n" +
	"\tsource_id\x18\b \x01(\tR\bsourceId\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\"H\n" +
	"\x0fEnqueueResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\"\xa3\x01\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12:\n" +
	"\vpop_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"popTimeout\"\x81\x03\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12*\n" +
	"\x06policy\x18\x06 \x01(\v2\x12.littleq.v1.PolicyR\x06policy\x12%\n" +
	"\x0eschema_version\x18\a \x01(\x05R\rschemaVersion\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"claimed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tclaimedAt\"\\\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x13\n" +
	"\x11HeartbeatResponse\"[\n" +
	"\x0fCompleteRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x12\n" +
	"\x10CompleteResponse\"o\n" +
	"\vFailRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x0e\n" +
	"\fFailResponse\"a\n" +
	"\x14ScalingEventsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\"\xa2\x02\n" +
	"\fScalingEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\x13recommended_workers\x18\x02 \x01(\x05R\x12recommendedWorkers\x12!\n" +
	"\farrival_rate\x18\x03 \x01(\x01R\varrivalRate\x12!\n" +
	"\fservice_rate\x18\x04 \x01(\x01R\vserviceRate\x12\x1f\n" +
	"\vqueue_depth\x18\x05 \x01(\x03R\n" +
	"queueDepth\x12:\n" +
	"\fscaling_mode\x18\x06 \x01(\x0e2\x17.littleq.v1.ScalingModeR\vscalingMode\x12*\n" +
	"\x02ts\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"W\n" +
	"\x0eMetricsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\"\xa7\x01\n" +
	"\x0fMetricsResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\farrival_rate\x18\x02 \x01(\x01R\varrivalRate\x12!\n" +
	"\fservice_rate\x18\x03 \x01(\x01R\vserviceRate\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x03R\n" +
	"queueDepth\x12\x19\n" +
	"\bavg_wait\x18\x05 \x01(\x01R\aavgWait\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd0\x01\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\bmax_wait\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\amaxWait\x12\x1f\n" +
	"\vaging_alpha\x18\x03 \x01(\x01R\n" +
	"agingAlpha\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12:\n" +
	"\fscaling_mode\x18\x05 \x01(\x0e2\x17.littleq.v1.ScalingModeR\vscalingMode*~\n" +
	"\vScalingMode\x12\x1c\n" +
	"\x18SCALING_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SCALING_MODE_AGGRESSIVE\x10\x01\x12\x19\n" +
	"\x15SCALING_MODE_BALANCED\x10\x02\x12\x19\n" +
	"\x15SCALING_MODE_ECONOMIC\x10\x032\xbb\x04\n" +
	"\tScheduler\x12B\n" +
	"\aEnqueue\x12\x1a.littleq.v1.EnqueueRequest\x1a\x1b.littleq.v1.EnqueueResponse\x12G\n" +
	"\tSubscribe\x12\x1c.littleq.v1.SubscribeRequest\x1a\x1a.littleq.v1.TaskAssignment0\x01\x12H\n" +
	"\tHeartbeat\x12\x1c.littleq.v1.HeartbeatRequest\x1a\x1d.littleq.v1.HeartbeatResponse\x12E\n" +
	"\bComplete\x12\x1b.littleq.v1.CompleteRequest\x1a\x1c.littleq.v1.CompleteResponse\x129\n" +
	"\x04Fail\x12\x17.littleq.v1.FailRequest\x1a\x18.littleq.v1.FailResponse\x12M\n" +
	"\rScalingEvents\x12 .littleq.v1.ScalingEventsRequest\x1a\x18.littleq.v1.ScalingEvent0\x01\x12E\n" +
	"\n" +
	"GetMetrics\x12\x1a.littleq.v1.MetricsRequest\x1a\x1b.littleq.v1.MetricsResponse\x12?\n" +
	"\x06Health\x12\x19.littleq.v1.HealthRequest\x1a\x1a.littleq.v1.HealthResponseB3Z1github.com/LittleQ-io/littleq/proto/littleq/v1;lqpbb\x06proto3"

var (
	file_proto_littleq_v1_scheduler_proto_rawDescOnce sync.Once
	file_proto_littleq_v1_scheduler_proto_rawDescData []byte
)

func file_proto_littleq_v1_scheduler_proto_rawDescGZIP() []byte {
	file_proto_littleq_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_littleq_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_littleq_v1_scheduler_proto_rawDesc), len(file_proto_littleq_v1_scheduler_proto_rawDesc)))
	})
	return file_proto_littleq_v1_scheduler_proto_rawDescData
}

var file_proto_littleq_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_littleq_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_littleq_v1_scheduler_proto_goTypes = []any{
	(ScalingMode)(0),              // 0: littleq.v1.ScalingMode
	(*EnqueueRequest)(nil),        // 1: littleq.v1.EnqueueRequest
	(*EnqueueResponse)(nil),       // 2: littleq.v1.EnqueueResponse
	(*SubscribeRequest)(nil),      // 3: littleq.v1.SubscribeRequest
	(*TaskAssignment)(nil),        // 4: littleq.v1.TaskAssignment
	(*HeartbeatRequest)(nil),      // 5: littleq.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: littleq.v1.HeartbeatResponse
	(*CompleteRequest)(nil),       // 7: littleq.v1.CompleteRequest
	(*CompleteResponse)(nil),      // 8: littleq.v1.CompleteResponse
	(*FailRequest)(nil),           // 9: littleq.v1.FailRequest
	(*FailResponse)(nil),          // 10: littleq.v1.FailResponse
	(*ScalingEventsRequest)(nil),  // 11: littleq.v1.ScalingEventsRequest
	(*ScalingEvent)(nil),          // 12: littleq.v1.ScalingEvent
	(*MetricsRequest)(nil),        // 13: littleq.v1.MetricsRequest
	(*MetricsResponse)(nil),       // 14: littleq.v1.MetricsResponse
	(*HealthRequest)(nil),         // 15: littleq.v1.HealthRequest
	(*HealthResponse)(nil),        // 16: littleq.v1.HealthResponse
	(*Policy)(nil),                // 17: littleq.v1.Policy
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_proto_littleq_v1_scheduler_proto_depIdxs = []int32{
	17, // 0: littleq.v1.EnqueueRequest.policy:type_name -> littleq.v1.Policy
	18, // 1: littleq.v1.SubscribeRequest.pop_timeout:type_name -> google.protobuf.Duration
	17, // 2: littleq.v1.TaskAssignment.policy:type_name -> littleq.v1.Policy
	19, // 3: littleq.v1.TaskAssignment.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: littleq.v1.TaskAssignment.claimed_at:type_name -> google.protobuf.Timestamp
	18, // 5: littleq.v1.ScalingEventsRequest.interval:type_name -> google.protobuf.Duration
	0,  // 6: littleq.v1.ScalingEvent.scaling_mode:type_name -> littleq.v1.ScalingMode
	19, // 7: littleq.v1.ScalingEvent.ts:type_name -> google.protobuf.Timestamp
	18, // 8: littleq.v1.MetricsRequest.window:type_name -> google.protobuf.Duration
	18, // 9: littleq.v1.Policy.max_wait:type_name -> google.protobuf.Duration
	0,  // 10: littleq.v1.Policy.scaling_mode:type_name -> littleq.v1.ScalingMode
	1,  // 11: littleq.v1.Scheduler.Enqueue:input_type -> littleq.v1.EnqueueRequest
	3,  // 12: littleq.v1.Scheduler.Subscribe:input_type -> littleq.v1.SubscribeRequest
	5,  // 13: littleq.v1.Scheduler.Heartbeat:input_type -> littleq.v1.HeartbeatRequest
	7,  // 14: littleq.v1.Scheduler.Complete:input_type -> littleq.v1.CompleteRequest
	9,  // 15: littleq.v1.Scheduler.Fail:input_type -> littleq.v1.FailRequest
	11, // 16: littleq.v1.Scheduler.ScalingEvents:input_type -> littleq.v1.ScalingEventsRequest
	13, // 17: littleq.v1.Scheduler.GetMetrics:input_type -> littleq.v1.MetricsRequest
	15, // 18: littleq.v1.Scheduler.Health:input_type -> littleq.v1.HealthRequest
	2,  // 19: littleq.v1.Scheduler.Enqueue:output_type -> littleq.v1.EnqueueResponse
	4,  // 20: littleq.v1.Scheduler.Subscribe:output_type -> littleq.v1.TaskAssignment
	6,  // 21: littleq.v1.Scheduler.Heartbeat:output_type -> littleq.v1.HeartbeatResponse
	8,  // 22: littleq.v1.Scheduler.Complete:output_type -> littleq.v1.CompleteResponse
	10, // 23: littleq.v1.Scheduler.Fail:output_type -> littleq.v1.FailResponse
	12, // 24: littleq.v1.Scheduler.ScalingEvents:output_type -> littleq.v1.ScalingEvent
	14, // 25: littleq.v1.Scheduler.GetMetrics:output_type -> littleq.v1.MetricsResponse
	16, // 26: littleq.v1.Scheduler.Health:output_type -> littleq.v1.HealthResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_littleq_v1_scheduler_proto_init() }
func file_proto_littleq_v1_scheduler_proto_init() {
	if File_proto_littleq_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_littleq_v1_scheduler_proto_rawDesc), len(file_proto_littleq_v1_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_littleq_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_littleq_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_littleq_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_littleq_v1_scheduler_proto_msgTypes,
	}.Build()
	File_proto_littleq_v1_scheduler_proto = out.File
	file_proto_littleq_v1_scheduler_proto_goTypes = nil
	file_proto_littleq_v1_scheduler_proto_depIdxs = nil
}
